# Generated by Django 2.0.13 on 2019-04-04 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('lastname', models.TextField(blank=True, null=True)),
                ('image', models.FileField(null=True, upload_to='', verbose_name='image')),
                ('login', models.TextField()),
                ('active', models.TextField(default=0)),
                ('email', models.TextField(blank=True, null=True)),
                ('isModel', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
